<a href="https://colab.research.google.com/github/Nishant-172-bot/Samsung-Innovation-Campus/blob/main/Divide_and_Conquer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tromino  Problem

In [35]:
def create_board(n):
  return [[0 for _ in range(n)] for _ in range(n)]


def twobytwo(board, start_row, start_col):
  filled = 1
  for i in range(start_row, start_row + 2):
    for j in range(start_col, start_col + 2):
      if board[i][j] != 'f':
        board[i][j] = filled
  return board

def original(board, n, start_row=0, start_col=0):
  if n == 2:
    return twobytwo(board, start_row, start_col)
  half_n = n // 2
  original(board, half_n, start_row, start_col)
  original(board, half_n, start_row, start_col + half_n)
  original(board, half_n, start_row + half_n, start_col)
  original(board, half_n, start_row + half_n, start_col + half_n)

  return board

In [36]:
board = create_board(8)

def fill(board,n):
  for i in range(0, n, 4):
    for j in range(0, n, 4):
      board[i][j] = 'f'
fill(board,8)
original(board, 8, 0, 0)

for r_idx, row in enumerate(board):
    for c_idx, val in enumerate(row):
        if val == 'f':
            board[r_idx][c_idx] = 0

board

[[0, 1, 1, 1, 0, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1],
 [0, 1, 1, 1, 0, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1]]

In [71]:
import numpy as np

In [72]:
b=np.array([[1,2,3],[4,5,6]])

In [74]:
b.shape

(2, 3)

In [75]:
b[0,1]

np.int64(2)

In [78]:
b[1:,1:]

array([[5, 6]])

In [79]:
a=np.array([[1,2,3],[3,4,5]])

In [80]:
a+b #broadcasting -> affects all

array([[ 2,  4,  6],
       [ 7,  9, 11]])

In [81]:
a.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [84]:
a.reshape(2,3)

array([[1, 2, 3],
       [3, 4, 5]])

In [87]:
b @ b.T

array([[14, 32],
       [32, 77]])

In [89]:
np.zeros([8,8], dtype=np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [90]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [96]:
b.reshape(1,3,2)

array([[[1, 2],
        [3, 4],
        [5, 6]]])